source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Nuke Demo' do
	pod 'Nuke', :path => '../'
	pod 'DFCache'
	pod 'Preheat', :git => 'https://github.com/kean/Preheat', :branch => 'swift3'
end
