source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target "Nuke Demo" do
	pod "Nuke", :path => "../"
	pod "Nuke-AnimatedImage-Plugin", :git => "https://github.com/kean/Nuke-AnimatedImage-Plugin"
	pod "Nuke-Alamofire-Plugin", :git => "https://github.com/kean/Nuke-Alamofire-Plugin"
	pod "DFCache"
	pod "Preheat", :git => "https://github.com/kean/Preheat"
end
