disabled_rules:
    - line_length

nesting:
    type_level:
        warning: 2

included:
    - Sources/

file_length:
    warning: 1000
    error: 1500

type_body_length:
    warning: 400
    error: 800

identifier_name:
    min_length:
        warning: 1

reporter: "xcode"
